<?php

namespace Boissiere\E4Bundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends EntityRepository
{
    public function findAllOrderedByDate()
    {
        return $this->getEntityManager()
          ->createQuery('Select ev.datedebut, ev.description, ev.datefin, ev.lieu, ev.nomevent 
                         FROM BoissiereE4Bundle:Events ev
                         ORDER BY ev.datedebut ASC')
            ->getResult();
    }

}
