<?php

namespace Boissiere\E4Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRepository extends EntityRepository
{
    public function findAllOrderedByDate()
    {
        return $this->getEntityManager()
            ->createQuery('Select g FROM Groups g ORDER BY g.nameGroup ASC')
            ->getResult();
    }

}
