<?php

namespace Boissiere\E4Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MembersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembersRepository extends EntityRepository
{
    public function findAllMembers()
    {
        return $this->getEntityManager()
            ->createQuery('Select em.namemember, em.description, em.instrument, em.picture
                         FROM BoissiereE4Bundle:Members em')
            ->getResult();
    }

}
